name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust Windows
      if: runner.os == 'Windows'
      run: |
        if (Get-Command "rustup" -ErrorAction SilentlyContinue) {
            rustup update
        } else {
            Invoke-WebRequest https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe -OutFile rustup-init.exe
            ./rustup-init.exe -y --profile minimal --default-toolchain stable
            echo ::add-path::%USERPROFILE%\.cargo\bin
        }

    - name: Rust version
      run: |
        cargo --version
        rustc --version

    - name: Check std
      run: cargo check --features std

    - name: Test
      run: cargo test
      env:
        RUST_TEST_THREADS: 1

    - name: Test x86
      run: |
        rustup target add i686-pc-windows-msvc
        cargo test --target i686-pc-windows-msvc
      env:
        RUST_TEST_THREADS: 1
